server:
  port: 8081

spring:
  config:
    import: security.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/koramarket?currentSchema=${DB_SCHEMA:auth_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      schema: ${DB_SCHEMA:auth_service}
  jpa:
    hibernate:
      ddl-auto: update # Crée/mise à jour les tables automatiquement
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:auth_service}
        format_sql: true
