spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/koramarket?currentSchema=${DB_SCHEMA:auth_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      schema: ${DB_SCHEMA:auth_service}

jwt:
  secret: ${JWT_SECRET:YourSecretKeyForJWTSigningAndEncryption}
  expiration: ${JWT_EXPIRATION_MS:86400000}