server:
  port: 8081
  servlet:
    context-path: /api/auth

spring:
  jpa:
    hibernate:
      ddl-auto: update # Crée/mise à jour les tables automatiquement
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:auth_service}
        format_sql: true

jwt:
  secret: ${JWT_SECRET:YourSecretKeyForJWTSigningAndEncryption}
  expiration: ${JWT_EXPIRATION_MS:86400000}