spring:
  jpa:
    open-in-view: false
    show-sql: false
    defer-datasource-initialization: true
    generate-ddl: false # Désactivé au profit de Flyway
    hibernate:
      ddl-auto: validate # Changé à validate pour production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        ddl-auto: validate