spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: public
        ddl-auto: update