spring:
  jpa:
    hibernate:
      ddl-auto: update # Crée/mise à jour les tables automatiquement
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:auth_service}
        format_sql: true