server:
  port: 8080
  forward-headers-strategy: framework  # important derrière Cloudflare/ngrok (X-Forwarded-* / HTTPS)

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            # En dev tu peux garder large. En prod, restreins à ton domaine + trycloudflare/ngrok.
            allowedOriginPatterns:
              - "http://localhost:*"
              - "https://localhost:*"
              - "https://*.trycloudflare.com"
              - "https://*.ngrok-free.app"
              - "https://*.ngrok.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Location
              - Content-Disposition
            allowCredentials: false   # important si allowedOriginPatterns est large
            maxAge: 3600

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
            - Path=/api/oauth-clients/**
            - Path=/api/roles/**
            - Path=/api/permissions/**
            - Path=/api/user-roles/**
            - Path=/api/role-permissions/**
            - Path=/api/sessions/**
            - Path=/api/users/**
            - Path=/api/audit-logs/**
            - Path=/api/audit/**
            - Path=/api/users/*/reset-password
            - Path=/api/vendor-requests/**
            - Path=/api/auth/profile/me
            - Path=/api/auth/profile/me/avatar
            - Path=/api/auth/impersonate
            - Path=/uploads/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCB
                fallback-uri: forward:/fallback/auth

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
            - Path=/api/categories/**
            - Path=/api/product-images/**
            - Path=/api/product-attributes/**
            - Path=/api/product-reviews/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
            - Path=/api/orders/my/**
            - Path=/api/order-items/**
            - Path=/api/order-status/**
            - Path=/api/order-payment/**
            - Path=/api/order-payment-status/**
            - Path=/api/order-payment-methods/**
            - Path=/api/payments/*/capture
            - Path=/api/refunds/**
            - Path=/api/orders/*/addresses
            - Path=/api/orders/*/addresses/**
            - Path=/api/orders/by-number/*/addresses/**
            - Path=/api/shipments/**
            - Path=/api/credit-notes/**
            - Path=/api/invoices/by-number/*
            - Path=/api/invoices/by-user/*
            - Path=/api/invoices/by-date-range/*
            - Path=/api/invoices/by-status/*
            - Path=/api/invoices/by-product/*
            - Path=/api/invoices/by-user-product/*
            - Path=/api/invoices/*/pdf
            - Path=/api/invoices/by-number/*/pdf

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
            - Path=/api/carts/**
            - Path=/api/carts/my

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**

        - id: ia-web3-service
          uri: lb://ia-web3-service
          predicates:
            - Path=/api/ia/**
            - Path=/api/recommendations/my
            - Path=/api/recommendations/feedback
            - Path=/api/recommendations/rebuild/**
