server:
  port: 8088

spring:
  config:
    import: security.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/koramarket?currentSchema=${DB_SCHEMA:ia_web3_service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      schema: ${DB_SCHEMA:ia_web3_service}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:ia_service}
        format_sql: true