server:
  port: 8088
  servlet:
    context-path: /api/ia

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/koramarket?currentSchema=${DB_SCHEMA:ia}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      schema: ${DB_SCHEMA:ia}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:ia}
        format_sql: tru