server:
  port: 8086
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/koramarket
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
