server:
  port: 8083
  servlet:
    context-path: /api/orders

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/koramarket?currentSchema=order_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: order_service
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: order_service
        format_sql: true