spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/koramarket?currentSchema=${DB_SCHEMA:products}&ApplicationName=product-service
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      schema: ${DB_SCHEMA:products}
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:products}
        format_sql: true
        jdbc:
          batch_size: 30