server:
  port: 8082
  servlet:
    context-path: /api/products

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/koramarket
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
